version: '3.8'

services:
  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile-cache
    container_name: volunteer
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_SOURCE:}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS:}
      JWT_SECRET: ${JWT_SECRET:}
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    networks:
      - volunteer-network
    restart: unless-stopped

networks:
  volunteer-network:
    driver: bridge